export default {
    eyes: {
        id: 5,
        status:"active",
        coverImage: "/book_of_eyes/BookOfEyes_4x3_01.jpg",
        route: "/publications/book_of_eyes",
        title: "Book of Eyes", 
        publicationYear: 2024,
        detail:"Softcover",
        stockQuantity: 50,
        // info: 'A Castle by the Sea is a 22-page publication by Brad Gilbert that collates images taken in Ischia, Italy in the summer of 2022. It has been designed to be disassembled allowing you to use images as individual or large-scale prints.“Although the memories might not depict the actual events 100% they still feel like the truth. The image can show something different but it shows the same truth as the memory and it’s nice to have a scene that only appears in your head. Which is what a moment in time really is. Every time I look back on these images it forms that mist of memories and I feel closer to rabbits near the sea.”',
        info: <div><p>The Book of Eyes contains 23 images of the human eye, photographed in the UK during 2021-2024.</p><br />
        <p>The impetus (perhaps subconscious) of the project comes from Boris Groys who, in Philosophy of Care, argues that the human body is worthy of the same reverence as art-objects.</p><br/>
        <p>"The human gaze does not see the human soul - that was the privilege of god. The human soul sees only the human body. Our rights are related to the image that we offer to the gaze of others… Art does not wait for a better society of the future - it immortalizes here and now… To fulfill its mission, the art museum should include humans. Because the human being is simply a body among other bodies, a thing among other things, humans can also be blessed with the museums immortality."</p></div>,
        images_location:"/book_of_eyes",
        variants: [],
        price: 12.00,
        shipping: 0,
    },
    castle_bts: {
        id: 4,
        status:"active",
        coverImage: "/castle_by_the_sea/Small_CBTS_Grey_00.jpg",
        route: "/publications/castle_by_the_sea",
        title: "Castle By the Sea", 
        publicationYear: 2024,
        detail:"Softcover",
        stockQuantity: 30,
        // info: 'A Castle by the Sea is a 22-page publication by Brad Gilbert that collates images taken in Ischia, Italy in the summer of 2022. It has been designed to be disassembled allowing you to use images as individual or large-scale prints.“Although the memories might not depict the actual events 100% they still feel like the truth. The image can show something different but it shows the same truth as the memory and it’s nice to have a scene that only appears in your head. Which is what a moment in time really is. Every time I look back on these images it forms that mist of memories and I feel closer to rabbits near the sea.”',
        info: <div><p>A Castle by the Sea is a 22-page publication by Brad Gilbert that collates images taken in Ischia, Italy in the summer of 2022. It has been designed to be disassembled allowing you to use images as individual or large-scale prints.</p><br/> <p>“Although the memories might not depict the actual events 100% they still feel like the truth. The image can show something different but it shows the same truth as the memory and it’s nice to have a scene that only appears in your head. Which is what a moment in time really is. Every time I look back on these images it forms that mist of memories and I feel closer to rabbits near the sea.”</p></div>,
        images_location:"/castle_by_the_sea",
        variants: [],
        price: 15.00,
        shipping: 0,
    },
    orpheus_st: {
        id:1,
        status: "active",
        coverImage: "/orpheus_st_paintings/Small_ND_3070.jpg",
        route: "/publications/orpheus_st_paintings",
        title: "Orpheus Street Paintings",
        publicationYear: 2023,
        detail:"Hardcover",
        stockQuantity: 150,
        info: "Orpheus Street Paintings is a 57 paged hardback book that collates the work of Nelson Diplexcito. The book introduces you to the artists studio setting and then showcases his body of work ranging from large scale oil on canvas to smaller oil on paper pieces. The book also contains an interview conducted by Jungwon Jay Hur about Diplexcitos practice.",
        images_location:"/orpheus_st_paintings",
        variants:[],
        price: 30.00,
        shipping: 0,
    },
    below_bunyan:{
        id:2,
        status:"active",
        coverImage: "/below_bunyan/Small_BelowBunyan_Grey_01.jpg",
        route: "/publications/below_bunyan",
        title: "Below Bunyan",
        publicationYear: 2021,
        detail:"Hardcover",
        stockQuantity: 30,
        info: "Below Bunyan is a book that represents the diverse artistic spirit of the next generation, captured through compelling details that reveal the interior world of an oft-overlooked phenomenon.",
        images_location:"/below_bunyan",
        variants: [],
        price: 15.00,
        shipping: 0,
    },
    babe_rainbow: {
        id: 3,
        status:"active",
        coverImage: "/babe_rainbow/Small_MHC_Zine_Grey_01.jpg",
        route: "/publications/babe_rainbow",
        title: "Mildly High on the Babe Rainbow", 
        publicationYear: 2023,
        detail:"Hardcover",
        stockQuantity: 15,
        info: "Mildly High on The Babe Rainbow combines London concert photography with selected lyrics to transport the reader into the audience at the venue. Each copy features a hand typewritten cover making every edition unique. The publication also comes with a black & white darkroom handprint from The Mild High Club at Moth Club.",
        images_location:"/babe_rainbow",
        variants: [],
        price: 15.00,
        shipping: 0,
    },
    
}
 